POST http://localhost:3000/allergies HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNTUwNX0.PSy1ZxJ_ileH4dpC4x_R4OYm9r96FypHD7qsnqqWR1A

{
    "name": "ibuprofen",
    "reactions": "",
    "notes": "",
    "current": false,
    "date": "05-23-2023"
}

### CREATE 2
POST http://localhost:3000/allergies HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNTUwNX0.PSy1ZxJ_ileH4dpC4x_R4OYm9r96FypHD7qsnqqWR1A

{
    "name": "tylenol",
    "reactions": "",
    "notes": "",
    "current": true,
    "date": "05-23-2023"
}

### CREATE 3
POST http://localhost:3000/allergies HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNTUwNX0.PSy1ZxJ_ileH4dpC4x_R4OYm9r96FypHD7qsnqqWR1A

{
    "name": "zinc",
    "reactions": "",
    "notes": "",
    "current": true,
    "date": "05-23-2023"
}

### CREATE 4
POST http://localhost:3000/allergies HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNTUwNX0.PSy1ZxJ_ileH4dpC4x_R4OYm9r96FypHD7qsnqqWR1A

{
    "name": "forgot name",
    "reactions": "",
    "notes": "",
    "current": true,
    "date": "01-01-2022"
}

### CREATE 5
POST http://localhost:3000/allergies HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNTUwNX0.PSy1ZxJ_ileH4dpC4x_R4OYm9r96FypHD7qsnqqWR1A

{
    "name": "sleep med",
    "reactions": "",
    "notes": "",
    "current": true,
    "date": "01-09-2022"
}


### RETRIEVE all documents.
GET http://localhost:3000/allergies HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNTUwNX0.PSy1ZxJ_ileH4dpC4x_R4OYm9r96FypHD7qsnqqWR1A

### RETRIEVE a document by its ID.
GET http://localhost:3000/allergies/6476f67e83133f857fceb685 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNTUwNX0.PSy1ZxJ_ileH4dpC4x_R4OYm9r96FypHD7qsnqqWR1A

### UPDATE one document's year, by ID.
### Replace the id in the following request with one that exists
### and update the title, year, and/or language:
PUT http://localhost:3000/allergies/6476f67e83133f857fceb685 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNTUwNX0.PSy1ZxJ_ileH4dpC4x_R4OYm9r96FypHD7qsnqqWR1A

{
    "allergyId": "6476f67e83133f857fceb685", 
    "name": "lala",
    "reactions": "Stomachace",
    "notes": "",
    "current": false,
    "date": "05-23-2023"
}

### DELETE by ID (no response provided)
DELETE http://localhost:3000/allergies/6476f67e83133f857fceb685 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNTUwNX0.PSy1ZxJ_ileH4dpC4x_R4OYm9r96FypHD7qsnqqWR1A


### DELETEs ALL documents!
DELETE http://localhost:3000/allergies/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNTUwNX0.PSy1ZxJ_ileH4dpC4x_R4OYm9r96FypHD7qsnqqWR1A

