POST http://localhost:3000/measurements HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcwYmFlNmRmYTRmODEwNzMzMWNiYSIsImlhdCI6MTY4NTUyMzM3NX0.UTo1rZrEyYQT_w341uDB_wj7S_svHRpXv8Eh99Lb1mM

{
  "type": "single",
  "name": "BS",
  "number": 90,
  "upperNumber": null,
  "lowerNumber": null,
  "date": "05-23-2023"
}


### CREATE 2
POST http://localhost:3000/measurements HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcwYmFlNmRmYTRmODEwNzMzMWNiYSIsImlhdCI6MTY4NTUyMzM3NX0.UTo1rZrEyYQT_w341uDB_wj7S_svHRpXv8Eh99Lb1mM

{
    "name": "BP",
    "upperNumber": 100,
    "lowerNumber": 80,
    "date": "05-23-2023",
    "single": false

}

### CREATE 3
POST http://localhost:3000/measurements HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcwYmFlNmRmYTRmODEwNzMzMWNiYSIsImlhdCI6MTY4NTUyMzM3NX0.UTo1rZrEyYQT_w341uDB_wj7S_svHRpXv8Eh99Lb1mM

{
    "name": "DoubleNum",
    "upperNumber": 120,
    "lowerNumber": 70,
    "date": "05-23-2023",
    "single": false
}

### CREATE 4
POST http://localhost:3000/measurements HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcwYmFlNmRmYTRmODEwNzMzMWNiYSIsImlhdCI6MTY4NTUyMzM3NX0.UTo1rZrEyYQT_w341uDB_wj7S_svHRpXv8Eh99Lb1mM

{
    "name": "SingleNum",
    "number": 80,
    "date": "05-23-2023",
    "single": true
}

### CREATE 5
POST http://localhost:3000/measurements HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcwYmFlNmRmYTRmODEwNzMzMWNiYSIsImlhdCI6MTY4NTUyMzM3NX0.UTo1rZrEyYQT_w341uDB_wj7S_svHRpXv8Eh99Lb1mM

{
    "name": "DoubleNum 2",
    "upperNumber": 110,
    "lowerNumber": 60,
    "date": "05-23-2023",
    "single": false
}

### RETRIEVE all documents.
GET http://localhost:3000/measurements HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcwYmFlNmRmYTRmODEwNzMzMWNiYSIsImlhdCI6MTY4NTUyMzM3NX0.UTo1rZrEyYQT_w341uDB_wj7S_svHRpXv8Eh99Lb1mM

### RETRIEVE a document by its ID.
GET http://localhost:3000/measurements/6477100a97b2191491c2393c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcwYmFlNmRmYTRmODEwNzMzMWNiYSIsImlhdCI6MTY4NTUyMzM3NX0.UTo1rZrEyYQT_w341uDB_wj7S_svHRpXv8Eh99Lb1mM

### UPDATE one document's year, by ID.
PUT http://localhost:3000/measurements/6477100a97b2191491c2393c HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcwYmFlNmRmYTRmODEwNzMzMWNiYSIsImlhdCI6MTY4NTUyMzM3NX0.UTo1rZrEyYQT_w341uDB_wj7S_svHRpXv8Eh99Lb1mM

{
  "name": "BS",
  "number": 1000,
  "upperNumber": null,
  "lowerNumber": null,
  "date": "05-23-2023"
}


### DELETE by ID (no response provided)
DELETE http://localhost:3000/measurements/6477100a97b2191491c2393c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcwYmFlNmRmYTRmODEwNzMzMWNiYSIsImlhdCI6MTY4NTUyMzM3NX0.UTo1rZrEyYQT_w341uDB_wj7S_svHRpXv8Eh99Lb1mM

### DELETEs ALL documents!
DELETE http://localhost:3000/measurements/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcwYmFlNmRmYTRmODEwNzMzMWNiYSIsImlhdCI6MTY4NTUyMzM3NX0.UTo1rZrEyYQT_w341uDB_wj7S_svHRpXv8Eh99Lb1mM
