POST http://localhost:3000/medications HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNzMwN30.AoWZHg78qqHDrUMdXa99RdL1GR8OAEUOLz9GITXkv6s

{
    "name": "ibuprofen",
    "dosage": 300,
    "unit": "mg",
    "instructions": "as needed, max 2times/day",
    "notes": "",
    "current": false,
    "date": "05-23-2023"
}

### CREATE 2
POST http://localhost:3000/medications HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNzMwN30.AoWZHg78qqHDrUMdXa99RdL1GR8OAEUOLz9GITXkv6s

{
    "name": "tylenol",
    "dosage": 600,
    "unit": "mg",
    "instructions": "as needed, max 2times/day",
    "notes": "",
    "current": true,
    "date": "05-23-2023"
}

### CREATE 3
POST http://localhost:3000/medications HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNzMwN30.AoWZHg78qqHDrUMdXa99RdL1GR8OAEUOLz9GITXkv6s

{
    "name": "zinc",
    "dosage": 30,
    "unit": "mg",
    "instructions": "pimple",
    "notes": "",
    "current": true,
    "date": "05-23-2023"
}

### CREATE 4
POST http://localhost:3000/medications HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNzMwN30.AoWZHg78qqHDrUMdXa99RdL1GR8OAEUOLz9GITXkv6s

{
    "name": "forgot name",
    "dosage": 50,
    "unit": "mg",
    "instructions": "depression",
    "notes": "",
    "current": true,
    "date": "01-01-2022"
}

### CREATE 5
POST http://localhost:3000/medications HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNzMwN30.AoWZHg78qqHDrUMdXa99RdL1GR8OAEUOLz9GITXkv6s

{
    "name": "sleep med",
    "dosage": 50,
    "unit": "mg",
    "instructions": "as needed, max 1/day",
    "notes": "",
    "current": true,
    "date": "01-09-2022"
}


### RETRIEVE all documents.
GET http://localhost:3000/medications HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNzMwN30.AoWZHg78qqHDrUMdXa99RdL1GR8OAEUOLz9GITXkv6s


### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/medications/6476fb1ba69aceca8debc73d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNzMwN30.AoWZHg78qqHDrUMdXa99RdL1GR8OAEUOLz9GITXkv6s


### UPDATE one document's year, by ID.
### Replace the id in the following request with one that exists
### and update the title, year, and/or language:
PUT http://localhost:3000/medications/6476fb1ba69aceca8debc73d HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNzMwN30.AoWZHg78qqHDrUMdXa99RdL1GR8OAEUOLz9GITXkv6s

{
    "name": "lalal",
    "dosage": 600,
    "unit": "mg",
    "instructions": "as needed, max 2times/day",
    "notes": "No longer use",
    "current": false,
    "date": "05-23-2023"
}

### DELETE by ID (no response provided)
DELETE http://localhost:3000/medications/6476fb1ba69aceca8debc73d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNzMwN30.AoWZHg78qqHDrUMdXa99RdL1GR8OAEUOLz9GITXkv6s


### DELETEs ALL documents!
DELETE http://localhost:3000/medications/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzZlY2VmOTg5NDcxM2YyZmNjNGRmNCIsImlhdCI6MTY4NTUxNzMwN30.AoWZHg78qqHDrUMdXa99RdL1GR8OAEUOLz9GITXkv6s

